### PR TITLE
Azurite TestContainer for Azure blob testing

### PR DESCRIPTION
**Pull request by andye2004**
Hi Paul, my curiosity got the better of me and I decided to look into the Azure docker container implementation.

It seemed obvious to me that it would be better to try it out with a real-world scenario, so I took the liberty of converting the Azure tests to use my test container implementation. There actually isn't much to this in the end but it now means the Azure tests could run without a pre-defined Azure set-up and would make development for spring-content noobs like myself easier moving forward.

I hope you don't mind that I have opened a PR but please feel free to reject it if this isn't a road you would want to go down.

Cheers, Andy.

### CODE REVIEW

**Comment by andye2004** [comment]
Sorry, can't help myself. I had to add a TC implementation for AWS. Also, I uncovered the issue causing the broken AWS test I mentioned before so I've fixed this as well.

**Comment by andye2004** [comment]
Nice to see your response re testcontainers, we use them a fair bit internally. Guess the good news would be that I have most of them already converted locally and working :)

**Comment by paulcwarren** [comment]
This also passed locally so merging this too.  Thanks very much @andye2004

**Comment by andye2004** [comment]
Hi @paulcwarren, I'll open another PR in the next day or two with all of the other test container conversion I have.

**Comment by paulcwarren** [comment]
Looking forward to seeing those.

Thankyou

**Pull request merged**
